const view=new URLSearchParams(location.search).get('view')||'task-edit';
const map=`<svg viewBox="0 0 760 430" role="img" aria-label="Fictional map: visitor parking west, marked footpath to welcome desk south of the building" xmlns="http://www.w3.org/2000/svg"><rect width="760" height="430" fill="#eff2e8"/><path d="M0 360H760" stroke="#ced3ca" stroke-width="70"/><text x="360" y="369" fill="#566158" font-size="18" font-family="sans-serif">EXAMPLE LANE</text><rect x="72" y="76" width="170" height="225" rx="12" fill="#dbe3d7" stroke="#a4b39e"/><text x="157" y="160" text-anchor="middle" font-size="20" fill="#344d3c" font-family="sans-serif">Visitor</text><text x="157" y="186" text-anchor="middle" font-size="20" fill="#344d3c" font-family="sans-serif">parking</text><rect x="358" y="72" width="310" height="182" rx="7" fill="#fff" stroke="#aebbae" stroke-width="2"/><text x="512" y="155" text-anchor="middle" font-size="22" font-family="sans-serif" fill="#344d3c">Example building</text><path d="M244 225L305 225L305 286L493 286L493 254" fill="none" stroke="#5e896b" stroke-width="8" stroke-dasharray="12 8"/><circle cx="493" cy="277" r="12" fill="#285847"/><text x="527" y="292" font-size="18" font-family="sans-serif" fill="#344d3c">Welcome desk</text><text x="25" y="30" font-size="13" font-family="sans-serif" fill="#65736b">FICTIONAL MAP · NOT FOR SITE USE · NOT TO SCALE</text></svg>`;
const head=(title,subtitle)=>`<div class="titlebar"><div><p class="eyebrow">LDC CEDAR VALLEY REMODEL · SYNTHETIC</p><h1>${title}</h1><p class="meta">${subtitle}</p></div></div>`;
const prompts='Who should volunteers report to?\nWhere should they check in?\nWhat time should they arrive?\nWhat should they bring or wear?\nAre there any special instructions?';
const pages={
'task-edit':()=>`${head('Edit welcome desk','Task library · Existing task preset')}<div class="grid"><section class="card"><h2>Assignment details</h2><p class="meta">Optional instructions volunteers will read with this work.</p><label class="field">Details for new scheduled work<textarea aria-label="Assignment details for preset" placeholder="${prompts}"></textarea><small>Suggestions appear in gray until you write. Use paragraphs for clarity.</small></label><div class="actions"><button class="primary" disabled>Save task</button><button disabled>Cancel</button></div><p class="preview-only">Concept only · This empty field has no saved content.</p></section><aside><section class="card"><h2>Existing assignments</h2><p>Changing a task preset does not silently rewrite scheduled items. Review any future dates that need an update.</p><a href="screen.html?view=occurrence">See an occurrence exception →</a></section><p class="foot">The current application creates presets but does not yet edit their description. This is the proposed narrow edit path.</p></aside></div>`,
'occurrence':()=>`${head('Welcome desk · October 6','Calendar · Exact scheduled item')}<div class="grid"><section class="card"><h2>Instructions for this date</h2><div class="choice"><strong>Use the task instructions</strong><p>Keep the reusable text already copied to this scheduled item.</p></div><div class="choice selected"><strong>Different instructions for this date</strong><p>Use the exception below for this occurrence only.</p></div><label class="field">Assignment details<textarea readonly>Report to the south entrance at 7:45 AM. Jordan Example will meet you at the welcome desk.\n\nFor October 6 only: use west visitor parking while the east area is closed. Bring sturdy closed-toe footwear and a refillable water bottle.</textarea><small>Other dates and existing responses stay unchanged.</small></label><div class="actions"><button class="primary" disabled>Save this date</button><button disabled>Cancel</button></div></section><aside class="card"><h2>Before volunteers see this</h2><p>Check the actual item and date, review the changed text and save with the current item version. The previous published wording remains in an administrative audit.</p><p class="meta">No automatic email is sent.</p></aside></div>`,
'assignment':()=>`<a class="back" href="index.html">← My schedule</a><div class="assignment-dialog"><div class="dialog-header"><p class="eyebrow">ASSIGNMENT DETAILS</p><h1>Welcome desk</h1><p>Tuesday, October 6 · 8:00 AM – 12:00 PM</p></div><div class="dialog-body"><dl class="facts"><div><dt>Current response</dt><dd><span class="badge neutral">Awaiting reply</span></dd></div><div><dt>Follow-up Contact</dt><dd>Jordan Example</dd></div></dl><details class="disclosure" id="details"><summary>Assignment details</summary><div>Report to the south entrance at 7:45 AM. Jordan Example will meet you at the welcome desk.\n\nFor October 6 only: use west visitor parking while the east area is closed. Bring sturdy closed-toe footwear and a refillable water bottle.</div></details><p><a href="screen.html?view=map-view">Open this project's site map ↗</a></p><hr class="divider"><h2>Can you attend?</h2><div class="actions"><button class="primary" disabled>Confirm</button><button disabled>Can't make it</button></div><p class="preview-only">Existing response workflow retained; controls are inactive in this design preview.</p></div></div>`,
'map-admin':()=>`${head('Project site map','One approved map for this project')}<div class="grid"><section class="card"><h2>Current map</h2><div class="map-preview">${map}</div><p class="meta" style="margin-top:14px">Illustrative site map · Approved example · Version 2</p><div class="actions"><button disabled>Replace map</button><button disabled>Remove map</button></div><p class="preview-only">Only authorized project contacts can manage this map.</p></section><aside><section class="card"><h2>Review a replacement</h2><div class="upload-box"><p>Select the exact coordinator-approved file. Preview and check labels before making it current.</p><button class="primary" disabled>Upload replacement</button></div><p class="foot" style="margin-top:14px">A failed validation keeps the current map. File-size limit follows the real approved file and tested delivery path.</p></section><div class="notice">Volunteers see the current approved map for their own project. A replacement appears only after it passes review.</div></aside></div>`,
'map-view':()=>`<a class="back" href="screen.html?view=assignment">← Assignment details</a>${head('Visitor site map','Fictional example · Current approved project map')}<div class="viewer"><div class="viewer-tools"><span class="meta">Project map · Page 1 of 1</span><div class="actions"><button id="zoom" aria-pressed="false">Zoom in</button><button id="fit">Fit page</button></div></div><div class="map-stage" tabindex="0" aria-label="Scrollable fictional site map">${map}</div></div><section class="card" style="margin-top:20px"><h2>Written directions</h2><p>From Example Lane, enter visitor parking on the west side. Follow the marked path to the welcome desk at the south entrance.</p><p class="foot">Synthetic directions. A real map and its accessible route description require coordinator approval.</p></section>`};
const admin=['task-edit','occurrence','map-admin'].includes(view);
const content=(pages[view]||pages['task-edit'])();
document.querySelector('#app').innerHTML=admin?`<div class="mobile-context">LDC Cedar Valley Remodel · ${view==='map-admin'?'Project settings':view==='task-edit'?'Task library':'Calendar'}</div><div class="shell"><nav class="sidebar" aria-label="Existing admin navigation context"><strong>LDC Cedar Valley<br>Remodel</strong><a href="index.html">Overview</a><a href="screen.html?view=occurrence" class="${view==='occurrence'?'active':''}">Calendar</a><a href="screen.html?view=task-edit" class="${view==='task-edit'?'active':''}">Task library</a><a href="screen.html?view=map-admin" class="${view==='map-admin'?'active':''}">Project settings</a></nav><main>${content}</main></div>`:`<main>${content}</main>`;
document.body.dataset.view=view;
document.title=`${document.querySelector('h1').textContent} · Project Local design`;
const zoom=document.querySelector('#zoom'),stage=document.querySelector('.map-stage');if(zoom){zoom.onclick=()=>{const on=stage.classList.toggle('zoomed');zoom.setAttribute('aria-pressed',String(on));zoom.textContent=on?'Zoom out':'Zoom in'};document.querySelector('#fit').onclick=()=>{stage.classList.remove('zoomed');zoom.setAttribute('aria-pressed','false');zoom.textContent='Zoom in'}}
